version: '3'
services:
  ev_db:
    container_name: ev-dim
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    mem_limit: 500M
    volumes:
      - after-dark-db:/var/lib/postgresql/data
  redis:
    image: 'redis:alpine'
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'

volumes:
  after-dark-db:
    external: true
