version: '3'
services:
  firestore:
    container_name: firestore
    image: mtlynch/firestore-emulator
    environment:
      - FIRESTORE_PROJECT_ID=${PROJECT_ID}
      - PORT=${FIRESTORE_PORT}
    ports:
      - '${FIRESTORE_PORT}:${FIRESTORE_PORT}'
    mem_limit: 500M
  redis:
    container_name: redis
    image: 'redis:alpine'
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    mem_limit: 500M

